project:
  type: website
  preview:
    port: 7100 

website:
  title: "Lin300-2026 - Speech Sounds"
  site-url: "https://Lin300-2026.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: course-materials/index.qmd
  sidebar: 
    - title: Home
      style: docked
      contents: /index.qmd
    # - title: Policies
    #   contents:
    #   - auto: policies/
    - title: Materials
      collapse-level: 3
      contents:
      - auto: course-materials/

format:
  html:
    theme:
      - flatly
      - brand
      - styles/custom.scss
    css: styles.css
    toc: true
  revealjs:
    center: true
    footer: |
      [HTML](./index.html) -- [PDF](./index.pdf)
    theme:
      - default
      - brand
      - styles/reveal.scss
    revealjs-plugins:
      - a11y
  typst:
    font-paths: 
      - fonts/

editor: visual

