---
title: "ipa"
draft: true
format: 
  html: 
    theme:
      - styles.scss  
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem

  typst:
    margin:
      x: 0.25cm
editor: visual
echo: false
crossref:
  tbl-title: ""     # (default is "Table")
---

```{r}

library(tibble)
library(tinytable)
library(purrr)
```

```{=typst}
#set text(font: "Noto Sans", size: 12pt, hyphenate: false)
#set align(center)
#show heading: set text(font: "Noto Sans", size: 10pt) 
#show heading: smallcaps
#show heading: set align(left)
```
# Consonants (Pulmonic) {.ipa}

```{r}
#| label: tbl-ipa-cons
#| classes: ".ipa"
#| tbl-cap: |
#|   Symbols to the right in a cell are voiced, to the left are voiceless. 
#|   Shaded areas denote articulations judged impossible.
#| tbl-cap-location: bottom
impossibles <- function(tab, coords){
  for(i in seq_along(coords)){
    tab <- tab |> 
      style_tt(
        i = coords[[i]][1],
        j = coords[[i]][2],
        background = "grey"
      )
  }
  tab
}

tribble(
  ~` `, ~Bilabial, ~Labiodental, ~Dental, ~Alveolar, ~Postalveolar, ~Retroflex, ~Palatal, ~Velar, ~Uvular, ~Pharyngeal, ~` `, ~Glottal,
  "Plosives", "p b", "",  "t d","", "", "ʈ ɖ", "c ɟ", "k g", "q ɢ", "", "  ", "ʔ",
  "Nasal", "m", "ɱ", "n", "", "", "ɳ", "ɲ", "ŋ", "ɴ", "", "","",
  "Trill", "ʙ", "", "r", "", "", "", "", "", "ʀ", "", "", "",
  "Tap or Flap", "", "ⱱ", "ɾ", "", "", "ɽ" , "", "", "", "", "", "",
  "Fricative", "ɸ β", "f v", "θ ð", "s z", "ʃ ʒ", "ʂ ʐ", "ç ʝ", "x ɣ", "χ ʁ", "ħ ʕ", "", "h ɦ",
  "Lateral Fricative", "", "", "ɬ ɮ", "", "", "", "", "", "", "", "", "",
  "Approximant", "", "ʋ" , "ɹ", "", "", "ɻ", "j", "ɰ", "", "", "", "",
  "Latteral approximant", "", "", "l", "" ,"", "ɭ", "ʎ", "ʟ", "", "", "", ""
) |> 
  tt() |> 
  style_tt(
    align = "c",
    line = "tblr"
  ) |> 
  style_tt(
    i = c(1:4, c(6:8)),
    j = 4,
    colspan = 3,
    align = "c"
  ) |> 
  style_tt(
    i = c(0,2:8),
    j = 11,
    colspan = 2,
    align = "c"
  )  |>
  style_tt(
    j = 1,
    fontsize = 0.7
  ) |> 
  style_tt(
    i = 0,
    fontsize = 0.7
  ) |>   
  impossibles(
    coords = list(
      c(1, 12),
      c(2, 11),
      c(2, 13),
      c(3, 9),
      c(3, 13),
      c(4, 9),
      c(4, 13),
      c(6, 2),
      c(6,3),
      c(6,11),
      c(6,13),
      c(7,13),
      c(8, 2),
      c(8, 3),
      c(8, 11),
      c(8, 13)
    )
  ) |> 
  
  identity()
```

::::::: {layout="[ 50, 50]"}
::: {}
# Other Symbols {.ipa}

```{r}
#| classes: .ipa
tribble(
  ~csym, ~cdesc,~impsym, ~impdesc, ~ejsym, ~ejdesc,
  "ʘ", "Bilabial", "ɓ", "Bilabial","ʼ", "Examples:",
  "ǀ", "Dental", "ɗ", "Dental/alveolar", "pʼ", "Bilabial",
  "ǃ", "(Post)alveolar", "ʄ", "Palatal", "tʼ", "Dental/alveolar",
  "ǂ", "Palatoalveolar", "ɠ", "velar", "k’", "velar",
  "ǁ", "Alveolar lateral", "ʛ", "Uvular", "sʼ", "Alveolar fricative"
) |> 
  tt(colnames = F) |> 
  tt_group(
    j = list(
      "Clicks" = 1:2,
      "Voiced Implosives" = 3:4,
      "Ejectives" = 5:6
    )
  ) |> 
  style_tt(
    j = c(1,3,5),
    line = "l"
  ) |> 
  style_tt(
    j = c(6),
    line = "r"
  ) |> 
  style_tt(
    j = c(2, 4, 6),
    fontsize = 0.7
  )
```
:::

::: {.ipa}

# Vowels {.ipa}

```{=html}
<svg width="300" height="200"
     xmlns="http://www.w3.org/2000/svg">
     
<text x="2" y="1em" font-size="1em" text-anchor="middle" fill="black">i</text>

</svg>
```

```{=typst}
#set align(right)
#let dot = box(height:1em)[#align(horizon)[#circle(radius:0.2em, fill: black)]]
#let hline(s, e) = {
  box(height: 1em)[#line(start: s, end: e)]
}

#box(height:20em, width:20em)[
i #dot y #hline((0%, 50%), (25%,50%)) ɨ #dot ʉ #hline((0%, 50%), (25%,50%)) ɯ #dot u 
#place(dy:25%)[e]#dot
]
```
:::

:::::::
